spring.application.name=jwt-auth
spring.mvc.apiversion.use.header=API-Version
spring.mvc.apiversion.default=1

# POSTGRES
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT:5432}/${POSTGRES_DB}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

# JWT
jwt.secret-key=${JWT_SECRET_KEY}
jwt.cookie.domain=${JWT_COOKIE_DOMAIN}

jwt.cookie.http-only=true
jwt.cookie.same-site=Lax

jwt.refresh.duration=31
jwt.refresh.duration-unit=DAYS

jwt.access.duration=15
jwt.access.duration-unit=MINUTES